name: Deploy to EC2 via SCP + SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Copy project files to EC2
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        source: "./"
        target: "~/devops-final"

    - name: Deploy and upload artifact to Nexus
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/devops-final

          echo "Limpiando contenedores antiguos"
          docker-compose down

          echo "Reconstruyendo imágenes"
          docker-compose build --no-cache

          echo "Levantando servicios"
          docker-compose up -d

          echo "Esperando que Nexus esté listo..."
          for i in {1..10}; do
            if curl -sSf http://localhost:8081 > /dev/null; then
              echo "Nexus está listo."
              break
            else
              echo "Esperando a Nexus... intento $i"
              sleep 10
            fi
          done

          echo "Empaquetando artefacto..."
          zip -r build.zip app run.py requirements.txt docker-compose.yml Dockerfile

          echo "Subiendo artefacto a Nexus..."
          curl -v -u admin:${{ secrets.NEXUS_PASSWORD }} \
          --upload-file build.zip \
          http://localhost:8081/repository/fastapi-artifacts/v1.0.0/build.zip

